#include "CalculationOfAccelerationResistanceOfSecondaryCircuitWaterRisingSpace.h"

CalculationOfAccelerationResistanceOfSecondaryCircuitWaterRisingSpace::CalculationOfAccelerationResistanceOfSecondaryCircuitWaterRisingSpace(/* args */)
{
}

CalculationOfAccelerationResistanceOfSecondaryCircuitWaterRisingSpace::~CalculationOfAccelerationResistanceOfSecondaryCircuitWaterRisingSpace()
{
}
