#include "CalculationOfTheResistanceOfTheWaterBendInTheSecondaryCircuitWaterRiseSpace.h"

CalculationOfTheResistanceOfTheWaterBendInTheSecondaryCircuitWaterRiseSpace::CalculationOfTheResistanceOfTheWaterBendInTheSecondaryCircuitWaterRiseSpace(/* args */)
{
}

CalculationOfTheResistanceOfTheWaterBendInTheSecondaryCircuitWaterRiseSpace::~CalculationOfTheResistanceOfTheWaterBendInTheSecondaryCircuitWaterRiseSpace()
{
}