#include "CalculationOfTotalResistanceOfSecondaryCircuitWaterCirculation.h"

CalculationOfTotalResistanceOfSecondaryCircuitWaterCirculation::CalculationOfTotalResistanceOfSecondaryCircuitWaterCirculation(/* args */)
{
}

CalculationOfTotalResistanceOfSecondaryCircuitWaterCirculation::~CalculationOfTotalResistanceOfSecondaryCircuitWaterCirculation()
{
}
