#include "CalculationOfTheTotalResistanceOfTheSecondaryCircuitWaterRisingSpace.h"


CalculationOfTheTotalResistanceOfTheSecondaryCircuitWaterRisingSpace::CalculationOfTheTotalResistanceOfTheSecondaryCircuitWaterRisingSpace(/* args */)
{
}

CalculationOfTheTotalResistanceOfTheSecondaryCircuitWaterRisingSpace::~CalculationOfTheTotalResistanceOfTheSecondaryCircuitWaterRisingSpace()
{
}

