#include "CalculationOfResistanceOfFlowDistributionOrificeInSecondaryWaterRisingSpace.h"

CalculationOfResistanceOfFlowDistributionOrificeInSecondaryWaterRisingSpace::CalculationOfResistanceOfFlowDistributionOrificeInSecondaryWaterRisingSpace(/* args */)
{
}

CalculationOfResistanceOfFlowDistributionOrificeInSecondaryWaterRisingSpace::~CalculationOfResistanceOfFlowDistributionOrificeInSecondaryWaterRisingSpace()
{
}
