#include "CalculationOfTheLocalResistanceOfTheSecondaryCircuitWaterRisingSpace.h"

CalculationOfTheLocalResistanceOfTheSecondaryCircuitWaterRisingSpace::CalculationOfTheLocalResistanceOfTheSecondaryCircuitWaterRisingSpace(/* args */)
{
}

CalculationOfTheLocalResistanceOfTheSecondaryCircuitWaterRisingSpace::~CalculationOfTheLocalResistanceOfTheSecondaryCircuitWaterRisingSpace()
{
}
