#include "CalculationOfTheFrictionalResistanceOfTheSecondaryCircuitWaterRisingSpace.h"

CalculationOfTheFrictionalResistanceOfTheSecondaryCircuitWaterRisingSpace::CalculationOfTheFrictionalResistanceOfTheSecondaryCircuitWaterRisingSpace(/* args */)
{
}

CalculationOfTheFrictionalResistanceOfTheSecondaryCircuitWaterRisingSpace::~CalculationOfTheFrictionalResistanceOfTheSecondaryCircuitWaterRisingSpace()
{
}
