#include "CalculationOfResistanceOfSecondaryCircuitWaterVaporSeparator.h"


CalculationOfResistanceOfSecondaryCircuitWaterVaporSeparator::CalculationOfResistanceOfSecondaryCircuitWaterVaporSeparator(/* args */)
{
}

CalculationOfResistanceOfSecondaryCircuitWaterVaporSeparator::~CalculationOfResistanceOfSecondaryCircuitWaterVaporSeparator()
{
}
