#include "CalculationOfTheSpaceResistanceOfTheSecondaryCircuitWaterDrop.h"


CalculationOfTheSpaceResistanceOfTheSecondaryCircuitWaterDrop::CalculationOfTheSpaceResistanceOfTheSecondaryCircuitWaterDrop(/* args */)
{
}

CalculationOfTheSpaceResistanceOfTheSecondaryCircuitWaterDrop::~CalculationOfTheSpaceResistanceOfTheSecondaryCircuitWaterDrop()
{
}
